### ISSUE TITLE
Unable to install with npm

### ISSUE THREAD

**Issue by cgmartin** [akarzim/hexo-tag-fontawesome#1]
Hi, this looks great to use but I wasn't able to install it with `npm` using the README instructions. Any plans to publish this? For now I've copied it as a custom tag in my `./scripts` folder.

Thanks for sharing this!

**Comment by akarzim** [comment]
Hi cgmartin, I just released v1.0.0 of hexo-tag-fontawesome on npm this morning.
Thanks for your feedback!

**Comment by cgmartin** [comment]
Awesome - I had been using a copy in a [theme I've been working on](https://github.com/cgmartin/hexo-theme-bootstrap-blog). I removed the copy and the `npm install` works great. Thanks again!
